//Blog
export const GET_BLOG_REQ = "GET_BLOG_REQ";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAILURE = "GET_BLOG_FAILURE";
//Blog Detail
export const BLOG_DETAIL_REQ = "BLOG_DETAIL_REQ";
export const BLOG_DETAIL_SUCCESS = "BLOG_DETAIL_SUCCESS";
export const BLOG_DETAIL_FAILURE = "BLOG_DETAIL_FAILURE";